# Generated by Django 4.0.3 on 2022-04-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galaxie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_de_decouverte', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
