# Generated by Django 4.0.3 on 2022-05-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_de_decouverte', models.DateField(blank=True, null=True)),
                ('distance', models.CharField(max_length=100)),
                ('taille_s', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Les galaxies spirales', 'Les galaxies spirales'), ('Les galaxies lenticulaires', 'Les galaxies lenticulaires '), ('Les galaxies elliptiques', ' Les galaxies elliptiques ')], default='Les galaxies spirales', max_length=40)),
                ('image_galaxie', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Pla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_de_decouverte', models.DateField(blank=True, null=True)),
                ('vitesse', models.CharField(max_length=100, null=True)),
                ('taille', models.CharField(max_length=100, null=True)),
                ('categorie', models.CharField(max_length=100)),
                ('image_planete', models.ImageField(null=True, upload_to='images')),
                ('galaxie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpla.galaxie')),
            ],
        ),
    ]
