# Generated by Django 4.0.3 on 2022-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxie',
            name='distance',
        ),
        migrations.AddField(
            model_name='galaxie',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pla',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
