# Generated by Django 4.0.3 on 2022-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpla', '0002_remove_galaxie_distance_galaxie_resume_pla_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxie',
            name='taille_s',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pla',
            name='taille',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pla',
            name='vitesse',
            field=models.IntegerField(null=True),
        ),
    ]
